### ISSUE TITLE
Support for native namespace packages?

### ISSUE THREAD

**Issue by jamesbraza** [Arkq/flake8-requirements#45]
I work at a company that uses [native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages) for multiple internal packages.

Let's say our namespace is `foo`, so in a given package `foo-ham` we have import statements like:

```python
from foo.bar import ...  # Import from internal package foo-bar
from foo.baz import ...  # Import from internal package foo-baz
from foo.spam import ...  # Import from internal package foo-spam
```

And in the `foo-ham` repo's `setup.py` we will have:

```python
install_requires=[
    "foo-bar"
    "foo-baz",
    "foo-spam",
],
```

Currently, `flake8-requirements` reports:

```
I900 'foo' not listed as a requirement
```

How can I get `flake8-requirements` to properly understand native namespace packages?

**Comment by Arkq** [comment]
You will have to add custom mappings. See this: https://github.com/Arkq/flake8-requirements#customization

**Comment by jamesbraza** [comment]
Okay I have added the `known-modules` to my `setup.cfg` like so:

```cfg
# Map namespace packages to imports for flake8-requirements
# SEE: https://github.com/Arkq/flake8-requirements#customization
known-modules = foo-bar:[foo.bar],foo-baz:[foo.baz],foo-spam:[foo.spam]
```

In actuality, I have a lot of namespace repos, and this `known-modules` line is longer than 120 chars.  Is there some way to line wrap this?  Support for this syntax would be desirable:

```cfg
known-modules =
    foo-bar:[foo.bar],
    foo-baz:[foo.baz],
    foo-spam:[foo.spam],
```

Also, one other question.  My python package is inside in a `src` directory from the repo root.  I invoke `flake8` via `pre-commit`:

```yaml
  - repo: "https://gitlab.com/pycqa/flake8"
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 src
        alias: flake8-src
        files: ^src/
        args:
          - "--config"
          - src/setup.cfg
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-requirements
```

Unfortunately, I find `flake8-requirements` doesn't work when invoked this way.  Any ideas why?
