### ISSUE TITLE
Does not recognize Poetry 1.2.0 `dev` section

### ISSUE THREAD

**Issue by nyuszika7h** [Arkq/flake8-requirements#55]
In Poetry 1.2.0, `[tool.poetry.dev-dependencies]` is now deprecated and is equivalent to `[tool.poetry.group.dev.dependencies]`. flake8-requirements does not appear to pick up the latter, as I have the following configuration:

```toml
[tool.poetry.group.dev.dependencies]
#...
Flake8-pyproject = "^1.1.0"
flake8-requirements = "^1.5.2"
#...
pyinstaller = "^5.3"
#...

[tool.flake8]
#...
known-modules = "...,pyinstaller:[PyInstaller],..."
#...
```

And I still get these error messages:
```
packaging/pyinstaller.py:9:1: I900 'PyInstaller' not listed as a requirement
packaging/pyinstaller.py:15:5: I900 'PyInstaller' not listed as a requirement
```

I'm running flake8-requirements 1.6.1.
